package com.tranche.bakery.order;

public enum OrderStatus {
    DRAFT,
    PENDING_CONFIRMATION,
    PENDING_PAYMENT_SCREENSHOT,
    PAYMENT_SCREENSHOT_RECEIVED,
    PAYMENT_SCREENSHOT_VERIFIED,
    PAYMENT_REVIEW_REQUIRED,
    CONFIRMED,
    CANCELLED,
    COMPLETED
}
